# Generated by Django 4.2.1 on 2023-06-19 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='code',
        ),
    ]
