# Generated by Django 4.2.1 on 2023-06-20 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='код'),
        ),
    ]
