# Generated by Django 4.2.1 on 2023-05-24 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('product_price',), 'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_count',
        ),
        migrations.AddField(
            model_name='category',
            name='category_text',
            field=models.CharField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='products',
            name='product_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category'),
        ),
        migrations.AddField(
            model_name='products',
            name='product_date_create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания'),
        ),
        migrations.AddField(
            model_name='products',
            name='product_date_edit',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='дата последнего изменения'),
        ),
        migrations.AddField(
            model_name='products',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_image/', verbose_name='изображение'),
        ),
        migrations.AddField(
            model_name='products',
            name='product_price',
            field=models.IntegerField(default=0, verbose_name='цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='product_text',
            field=models.TextField(blank=True, null=True, verbose_name='описание товара'),
        ),
    ]
