# Generated by Django 4.2.1 on 2023-05-24 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_products_options_remove_products_product_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('product_category',), 'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
    ]
