# Generated by Django 4.2.1 on 2023-06-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_products_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='заголовок')),
                ('slug', models.CharField(max_length=150, verbose_name='slug')),
                ('text', models.TextField(blank=True, null=True, verbose_name='содержимое')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_image/', verbose_name='изображение')),
                ('date_create', models.DateField(auto_now_add=True, null=True, verbose_name='дата создания')),
                ('view_count', models.IntegerField()),
                ('category', models.CharField(max_length=150, verbose_name='категория')),
            ],
            options={
                'verbose_name': 'статья',
                'verbose_name_plural': 'статьи',
                'ordering': ('view_count',),
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_text', models.TextField(blank=True, null=True, verbose_name='описание товара')),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='product_date_create',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_date_edit',
            field=models.DateField(auto_now=True, null=True, verbose_name='дата последнего изменения'),
        ),
    ]
