# Generated by Django 4.2.1 on 2023-06-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_blog_contacts_alter_products_product_date_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='view_count',
            field=models.IntegerField(default=1),
        ),
    ]
