# Generated by Django 4.2.1 on 2023-06-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_blog_category_blog_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='публикация'),
        ),
    ]
